"""followers

Revision ID: 86658a5ba4d4
Revises: 9af1af8fc9aa
Create Date: 2022-04-07 12:37:24.054438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86658a5ba4d4'
down_revision = '9af1af8fc9aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
